/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.TipoAccion;
import control.Utilities;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import modelo.Exchange;
import modelo.Peticion;

/**
 *
 * @author muril
 */
public class PanelComprar extends javax.swing.JPanel {

    /**
     * Creates new form PanelComprar
     */
    public JPanel mainList;
    public JPanel panelPublicaciones;
    
    public PanelComprar() {
        initComponents();
        
        panelPublicaciones = lbPublicaciones;        
        lbPublicaciones.setLayout(new BorderLayout());
        
        mainList = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridheight = GridBagConstraints.REMAINDER;
        gbc.weightx = 1;
        gbc.weighty = 1;
        JPanel p = new JPanel();
        p.setBackground(new Color(255,255,255));
        mainList.setBackground(new Color(255,255,255));
        mainList.add(p, gbc);

        lbPublicaciones.add(new JScrollPane(mainList));
        
        lbPublicaciones.validate();
        lbPublicaciones.repaint();
        
    }
    
    public void loadDatos(){
        Peticion peticion = new Peticion(TipoAccion.LOAD_EXCHANGES, "");        
        Client conexion = new Client(peticion);
        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            ArrayList<Exchange> walterMercado = (ArrayList)respuesta;
            for (Exchange i: walterMercado) {                
                GridBagConstraints gbc = new GridBagConstraints();
                gbc.gridheight = 1;
                gbc.weightx = GridBagConstraints.REMAINDER;
                gbc.fill = GridBagConstraints.HORIZONTAL;
                mainList.add(new PanelPublicaciones(i), gbc, 0);               
                
            }
            MainWindow.panelComprar.panelPublicaciones.validate();
            MainWindow.panelComprar.panelPublicaciones.repaint();
        }
        
        lbCantidadDinero1.setText(String.valueOf(MainWindow.player.getMoney()));
        
    }
    public void cleanExchange(){
        mainList.removeAll();
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridheight = GridBagConstraints.REMAINDER;
        gbc.weightx = 1;
        gbc.weighty = 1;
        JPanel p = new JPanel();
        p.setBackground(new Color(255,255,255));
        mainList.setBackground(new Color(255,255,255));
        mainList.add(p, gbc);
    }
    
    private String getStringImg(String nombre){
        String imagen = "";
        if (nombre.equals("Cannon")){
            imagen = "src\\images\\canon.png"; 
        }else if (nombre.equals("Cannon Multiple")){
            imagen = "src\\images\\canonMultiple.png";
        }else if(nombre.equals("Bomba")){
            imagen = "src\\images\\bomba.png";
        }else if(nombre.equals("Cannon Barba Roja")){
            imagen = "src\\images\\cañonBarbaRoja.png";
        }else if(nombre.equals("Acero")){
            imagen = "src\\images\\acero.png";
        }
        return imagen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBack = new javax.swing.JLabel();
        lbPublicaciones = new javax.swing.JPanel();
        lbCalavera = new javax.swing.JLabel();
        lbComprarMercado = new javax.swing.JLabel();
        lbDinero = new javax.swing.JLabel();
        lbCantidadDinero1 = new javax.swing.JLabel();
        lbSombrero = new javax.swing.JLabel();
        lbBandera = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        lbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });
        add(lbBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 70));

        lbPublicaciones.setBackground(new java.awt.Color(165, 173, 167));

        javax.swing.GroupLayout lbPublicacionesLayout = new javax.swing.GroupLayout(lbPublicaciones);
        lbPublicaciones.setLayout(lbPublicacionesLayout);
        lbPublicacionesLayout.setHorizontalGroup(
            lbPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1840, Short.MAX_VALUE)
        );
        lbPublicacionesLayout.setVerticalGroup(
            lbPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        add(lbPublicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1840, 310));

        lbCalavera.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbCalavera.setForeground(new java.awt.Color(0, 0, 0));
        lbCalavera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calavera.png"))); // NOI18N
        add(lbCalavera, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 270, 260));

        lbComprarMercado.setFont(new java.awt.Font("Roboto Light", 1, 36)); // NOI18N
        lbComprarMercado.setForeground(new java.awt.Color(0, 0, 0));
        lbComprarMercado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbComprarMercado.setText("Comprar en el mercado");
        add(lbComprarMercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 490, -1));

        lbDinero.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbDinero.setForeground(new java.awt.Color(0, 0, 0));
        lbDinero.setText("Dinero:");
        add(lbDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 90, -1));

        lbCantidadDinero1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbCantidadDinero1.setForeground(new java.awt.Color(0, 0, 0));
        lbCantidadDinero1.setText("0000000000");
        add(lbCantidadDinero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 180, -1));

        lbSombrero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbSombrero.setForeground(new java.awt.Color(0, 0, 0));
        lbSombrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sombrero.png"))); // NOI18N
        add(lbSombrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, 140));

        lbBandera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBandera.setForeground(new java.awt.Color(0, 0, 0));
        lbBandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bandera.png"))); // NOI18N
        add(lbBandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 80, 140, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        Utilities.cargarPanel(MainWindow.contentPanel, MainWindow.panelMercado);
    }//GEN-LAST:event_lbBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBack;
    private javax.swing.JLabel lbBandera;
    private javax.swing.JLabel lbCalavera;
    private javax.swing.JLabel lbCantidadDinero1;
    private javax.swing.JLabel lbComprarMercado;
    private javax.swing.JLabel lbDinero;
    private javax.swing.JPanel lbPublicaciones;
    private javax.swing.JLabel lbSombrero;
    // End of variables declaration//GEN-END:variables
}
