/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author ytces
 */
public class PanelTienda extends javax.swing.JPanel {
    public PanelEdificios panelEdificios;
    /**
     * Creates new form PanelTienda
     */
    public PanelTienda() {
        initComponents();
        panelEdificios = new PanelEdificios();
        cargarPanel(panelEdificios);
    }

    public void cargarPanel(JPanel panel) {
        otroPanel.removeAll();
        otroPanel.add(panel);
        otroPanel.repaint();
        otroPanel.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        otroPanel = new javax.swing.JPanel();
        btnArmas = new javax.swing.JButton();
        btnEdificios = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout otroPanelLayout = new javax.swing.GroupLayout(otroPanel);
        otroPanel.setLayout(otroPanelLayout);
        otroPanelLayout.setHorizontalGroup(
            otroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        otroPanelLayout.setVerticalGroup(
            otroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        add(otroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1300, 580));

        btnArmas.setText("Armas");
        btnArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArmasActionPerformed(evt);
            }
        });
        add(btnArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 220, 50));

        btnEdificios.setText("Edificios");
        btnEdificios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdificiosMouseClicked(evt);
            }
        });
        add(btnEdificios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 220, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArmasActionPerformed

    private void btnEdificiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdificiosMouseClicked
        
    }//GEN-LAST:event_btnEdificiosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArmas;
    private javax.swing.JButton btnEdificios;
    private javax.swing.JPanel otroPanel;
    // End of variables declaration//GEN-END:variables
}
