/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlTienda;
import control.IConstantes;
import control.TipoAccion;
import javax.swing.JOptionPane;
import modelo.Message;
import modelo.Peticion;
import javax.swing.JLabel;
import control.Utilities;
import java.awt.Color;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Random;
import modelo.Arma;
import modelo.Punto;
import modelo.Vertice;




/**
 *
 * @author ytces
 */
public class PanelJuego extends javax.swing.JPanel {
    public PanelMar panelMar1, panelMar2;
    public ControlTienda controlTienda;   
    public int lastUsed = -1;
    public int lastEnemy = -1;
    
    private boolean flagCargado = false;
    
    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
        controlTienda = new ControlTienda();
        panelMar1 = new PanelMar(0);
        panelMar2 = new PanelMar(1);
        Utilities.cargarPanel(myPanel, panelMar1);
        Utilities.cargarPanel(enemyPanel, panelMar2);
        
        for(int i=0; i<20; i++ ){
            JLabel lb = new JLabel();
            lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lb.setText(String.valueOf(i));
            panelCoordinates.add(lb);
        }
        
        imgCannon.setIcon(Utilities.loadResizeIcon("src\\images\\canon.png", 110));
        imgBomba.setIcon(Utilities.loadResizeIcon("src\\images\\bomba.png", 110));
        imgCannonM.setIcon(Utilities.loadResizeIcon("src\\images\\canonMultiple.png", 110));
        imgCannonB.setIcon(Utilities.loadResizeIcon("src\\images\\cañonBarbaRoja.png", 110));
    }
    
    public void loadDatos(){
        
        Thread th = new Thread(){
        @Override
        public void run(){
            try {
                while(true){                    
                    
                    MainWindow.getPlayer();
                    if(MainWindow.player.isTurn()){
                        btnFire.setEnabled(true);
                    }else{
                         btnFire.setEnabled(false);
                    }                    
                    ArrayList datos = MainWindow.player.cantidadArmas();
                    lbPlayerName.setText(MainWindow.player.getName());
                    lbCantCannon.setText(String.valueOf(datos.get(0)));
                    lbCantCannonM.setText(String.valueOf(datos.get(1)));
                    lbCantBomba.setText(String.valueOf(datos.get(2)));
                    lbCantCannonB.setText(String.valueOf(datos.get(3)));
                    panelMar1.updateCanvas();
                    Thread.sleep(1000);                    
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        };th.start();
        cargarHost();
        
        
    }
    
    public void cargarHost(){
        if(MainWindow.player.getId() == 0){
            lbState.setText("HOST");
            btnHost.setVisible(true);
        }else{
            lbState.setText("GUEST");
            btnHost.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        enemyPanel = new javax.swing.JPanel();
        panelArmas = new javax.swing.JPanel();
        lbPlayerName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelCannon = new javax.swing.JPanel();
        lbCañon = new javax.swing.JLabel();
        btnCannon = new javax.swing.JPanel();
        imgCannon = new javax.swing.JLabel();
        lbCantCannon = new javax.swing.JLabel();
        panelBomba = new javax.swing.JPanel();
        lbBomba = new javax.swing.JLabel();
        btnBomba = new javax.swing.JPanel();
        imgBomba = new javax.swing.JLabel();
        lbCantBomba = new javax.swing.JLabel();
        panelCannonM = new javax.swing.JPanel();
        lbCannonM = new javax.swing.JLabel();
        btnCannonM = new javax.swing.JPanel();
        imgCannonM = new javax.swing.JLabel();
        lbCantCannonM = new javax.swing.JLabel();
        panelCannonBR = new javax.swing.JPanel();
        lbCannonB = new javax.swing.JLabel();
        btnCannonB = new javax.swing.JPanel();
        imgCannonB = new javax.swing.JLabel();
        lbCantCannonB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        lbState = new javax.swing.JLabel();
        chatPanel = new javax.swing.JPanel();
        activatePanel = new javax.swing.JPanel();
        btnActivateChat = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        txtMsg = new javax.swing.JTextField();
        btnSendMsg = new javax.swing.JLabel();
        lbBarco = new javax.swing.JLabel();
        panelBitacora = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBitacora = new javax.swing.JTextArea();
        lbCoordenada5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnFire = new javax.swing.JButton();
        txtCoordenadaY = new javax.swing.JTextField();
        lbCoordenada2 = new javax.swing.JLabel();
        txtCoordenadaX = new javax.swing.JTextField();
        lbCoordenada = new javax.swing.JLabel();
        lbCoordenada4 = new javax.swing.JLabel();
        btnMercado = new javax.swing.JButton();
        btnReady = new javax.swing.JButton();
        btnHost = new javax.swing.JButton();
        lbCoordenada6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelCoordinates = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbPlayer3 = new javax.swing.JLabel();
        lbPlayer0 = new javax.swing.JLabel();
        lbPlayer1 = new javax.swing.JLabel();
        lbPlayer2 = new javax.swing.JLabel();
        btnLoadSeaEnemy = new javax.swing.JButton();

        setBackground(new java.awt.Color(120, 120, 120));
        setPreferredSize(new java.awt.Dimension(1900, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myPanel.setBackground(new java.awt.Color(255, 0, 0));
        myPanel.setLayout(new java.awt.CardLayout());
        add(myPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 640, 640));

        enemyPanel.setBackground(new java.awt.Color(255, 0, 0));
        enemyPanel.setLayout(new java.awt.CardLayout());
        add(enemyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 640, 640));

        panelArmas.setBackground(new java.awt.Color(165, 173, 167));
        panelArmas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPlayerName.setFont(new java.awt.Font("Roboto Light", 0, 30)); // NOI18N
        lbPlayerName.setForeground(new java.awt.Color(0, 0, 0));
        lbPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayerName.setText("Armas");
        panelArmas.add(lbPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 290, 29));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        panelArmas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelCannon.setBackground(new java.awt.Color(120, 120, 120));
        panelCannon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCannonMouseClicked(evt);
            }
        });
        panelCannon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCañon.setBackground(new java.awt.Color(0, 0, 0));
        lbCañon.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        lbCañon.setForeground(new java.awt.Color(0, 0, 0));
        lbCañon.setText("Cañón");
        lbCañon.setToolTipText("");
        panelCannon.add(lbCañon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, 40));

        btnCannon.setBackground(new java.awt.Color(212, 212, 212));
        btnCannon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCannonMouseClicked(evt);
            }
        });
        btnCannon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgCannon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/canon.png"))); // NOI18N
        btnCannon.add(imgCannon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 110));

        panelCannon.add(btnCannon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        lbCantCannon.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCantCannon.setForeground(new java.awt.Color(0, 0, 0));
        lbCantCannon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantCannon.setText("Cantidad");
        lbCantCannon.setPreferredSize(new java.awt.Dimension(100, 22));
        panelCannon.add(lbCantCannon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, -1));

        panelArmas.add(panelCannon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        panelBomba.setBackground(new java.awt.Color(120, 120, 120));
        panelBomba.setPreferredSize(new java.awt.Dimension(181, 220));
        panelBomba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBombaMouseClicked(evt);
            }
        });
        panelBomba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBomba.setBackground(new java.awt.Color(0, 0, 0));
        lbBomba.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        lbBomba.setForeground(new java.awt.Color(0, 0, 0));
        lbBomba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBomba.setText("Bomba");
        lbBomba.setToolTipText("");
        panelBomba.add(lbBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 6, 190, 30));

        btnBomba.setBackground(new java.awt.Color(212, 212, 212));
        btnBomba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBombaMouseClicked(evt);
            }
        });
        btnBomba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgBomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/canonMultiple.png"))); // NOI18N
        btnBomba.add(imgBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 110));

        panelBomba.add(btnBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 120));

        lbCantBomba.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCantBomba.setForeground(new java.awt.Color(0, 0, 0));
        lbCantBomba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantBomba.setText("Cantidad");
        lbCantBomba.setPreferredSize(new java.awt.Dimension(100, 22));
        panelBomba.add(lbCantBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, -1));

        panelArmas.add(panelBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 190, 210));

        panelCannonM.setBackground(new java.awt.Color(120, 120, 120));
        panelCannonM.setPreferredSize(new java.awt.Dimension(181, 220));
        panelCannonM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCannonMMouseClicked(evt);
            }
        });
        panelCannonM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCannonM.setBackground(new java.awt.Color(0, 0, 0));
        lbCannonM.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        lbCannonM.setForeground(new java.awt.Color(0, 0, 0));
        lbCannonM.setText("Cañón múltiple");
        lbCannonM.setToolTipText("");
        panelCannonM.add(lbCannonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 6, -1, 40));

        btnCannonM.setBackground(new java.awt.Color(212, 212, 212));
        btnCannonM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCannonMMouseClicked(evt);
            }
        });
        btnCannonM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgCannonM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/canonMultiple.png"))); // NOI18N
        btnCannonM.add(imgCannonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 110));

        panelCannonM.add(btnCannonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 52, 150, -1));

        lbCantCannonM.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCantCannonM.setForeground(new java.awt.Color(0, 0, 0));
        lbCantCannonM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantCannonM.setText("Cantidad");
        lbCantCannonM.setPreferredSize(new java.awt.Dimension(100, 22));
        panelCannonM.add(lbCantCannonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, 150, -1));

        panelArmas.add(panelCannonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 190, 210));

        panelCannonBR.setBackground(new java.awt.Color(120, 120, 120));
        panelCannonBR.setPreferredSize(new java.awt.Dimension(181, 220));
        panelCannonBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCannonBRMouseClicked(evt);
            }
        });
        panelCannonBR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCannonB.setBackground(new java.awt.Color(0, 0, 0));
        lbCannonB.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        lbCannonB.setForeground(new java.awt.Color(0, 0, 0));
        lbCannonB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCannonB.setText("Cañón Barba Roja");
        lbCannonB.setToolTipText("");
        panelCannonBR.add(lbCannonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 169, 40));

        btnCannonB.setBackground(new java.awt.Color(212, 212, 212));
        btnCannonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCannonBMouseClicked(evt);
            }
        });
        btnCannonB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgCannonB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/canonMultiple.png"))); // NOI18N
        btnCannonB.add(imgCannonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 110));

        panelCannonBR.add(btnCannonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        lbCantCannonB.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCantCannonB.setForeground(new java.awt.Color(0, 0, 0));
        lbCantCannonB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCantCannonB.setText("Cantidad");
        lbCantCannonB.setPreferredSize(new java.awt.Dimension(100, 22));
        panelCannonBR.add(lbCantCannonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, -1));

        panelArmas.add(panelCannonBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 190, 210));

        add(panelArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 1000));

        jLabel3.setText("   0         1         2         3        4         5        6         7        8        9       10      11      12      13      14      15      16      17      18      19");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 650, -1));

        panelBotones.setBackground(new java.awt.Color(165, 173, 167));
        panelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbState.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbState.setForeground(new java.awt.Color(0, 0, 0));
        lbState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbState.setText("Bitácora");
        panelBotones.add(lbState, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 20, 200, 40));

        chatPanel.setLayout(new java.awt.CardLayout());

        activatePanel.setLayout(new java.awt.CardLayout());

        btnActivateChat.setBackground(new java.awt.Color(86, 73, 64));
        btnActivateChat.setFont(new java.awt.Font("Roboto Light", 1, 36)); // NOI18N
        btnActivateChat.setForeground(new java.awt.Color(255, 255, 255));
        btnActivateChat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActivateChat.setText("Activate Chat");
        btnActivateChat.setIconTextGap(20);
        btnActivateChat.setOpaque(true);
        btnActivateChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivateChatMouseClicked(evt);
            }
        });
        activatePanel.add(btnActivateChat, "card3");

        optionPanel.setName("optionPanel"); // NOI18N
        optionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtChat.setEditable(false);
        txtChat.setBackground(new java.awt.Color(18, 30, 49));
        txtChat.setColumns(20);
        txtChat.setForeground(new java.awt.Color(255, 255, 255));
        txtChat.setRows(5);
        jScrollPane1.setViewportView(txtChat);

        optionPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 200));

        txtMsg.setBackground(new java.awt.Color(18, 30, 50));
        txtMsg.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtMsg.setForeground(new java.awt.Color(255, 255, 255));
        optionPanel.add(txtMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 35));

        btnSendMsg.setBackground(new java.awt.Color(86, 73, 64));
        btnSendMsg.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        btnSendMsg.setForeground(new java.awt.Color(255, 255, 255));
        btnSendMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSendMsg.setText("SEND");
        btnSendMsg.setIconTextGap(20);
        btnSendMsg.setOpaque(true);
        btnSendMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMsgMouseClicked(evt);
            }
        });
        optionPanel.add(btnSendMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 130, 35));

        activatePanel.add(optionPanel, "card2");

        chatPanel.add(activatePanel, "card3");

        panelBotones.add(chatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 430, 250));

        lbBarco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBarco.setForeground(new java.awt.Color(0, 0, 0));
        lbBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barco.png"))); // NOI18N
        panelBotones.add(lbBarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 130, 120));

        panelBitacora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBitacora.setEditable(false);
        txtBitacora.setBackground(new java.awt.Color(18, 30, 49));
        txtBitacora.setColumns(20);
        txtBitacora.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtBitacora.setForeground(new java.awt.Color(255, 255, 255));
        txtBitacora.setRows(5);
        jScrollPane2.setViewportView(txtBitacora);

        panelBitacora.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 388, 250));

        panelBotones.add(panelBitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, -1, 250));

        lbCoordenada5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCoordenada5.setForeground(new java.awt.Color(0, 0, 0));
        lbCoordenada5.setText("Opciones");
        panelBotones.add(lbCoordenada5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 90, -1));

        jPanel1.setBackground(new java.awt.Color(120, 120, 120));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFire.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFire.setText("Disparar");
        btnFire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFireMouseClicked(evt);
            }
        });
        jPanel1.add(btnFire, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, 30));

        txtCoordenadaY.setBackground(new java.awt.Color(212, 212, 212));
        txtCoordenadaY.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCoordenadaY.setForeground(new java.awt.Color(99, 99, 99));
        txtCoordenadaY.setBorder(null);
        jPanel1.add(txtCoordenadaY, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 30));

        lbCoordenada2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCoordenada2.setForeground(new java.awt.Color(0, 0, 0));
        lbCoordenada2.setText("Coordenada en Y:");
        jPanel1.add(lbCoordenada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtCoordenadaX.setBackground(new java.awt.Color(212, 212, 212));
        txtCoordenadaX.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCoordenadaX.setForeground(new java.awt.Color(99, 99, 99));
        txtCoordenadaX.setBorder(null);
        jPanel1.add(txtCoordenadaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 30));

        lbCoordenada.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCoordenada.setForeground(new java.awt.Color(0, 0, 0));
        lbCoordenada.setText("Coordenada en X:");
        jPanel1.add(lbCoordenada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lbCoordenada4.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lbCoordenada4.setForeground(new java.awt.Color(0, 0, 0));
        lbCoordenada4.setText("Indique las coordenadas");
        jPanel1.add(lbCoordenada4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panelBotones.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 260));

        btnMercado.setText("Opciones de Mercado");
        btnMercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMercadoMouseClicked(evt);
            }
        });
        btnMercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMercadoActionPerformed(evt);
            }
        });
        panelBotones.add(btnMercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 150, 50));

        btnReady.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnReady.setText("I'm Ready");
        btnReady.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadyMouseClicked(evt);
            }
        });
        panelBotones.add(btnReady, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 80, 210, 70));

        btnHost.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnHost.setText("Start Game");
        btnHost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHostMouseClicked(evt);
            }
        });
        panelBotones.add(btnHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 170, 210, 70));

        lbCoordenada6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCoordenada6.setForeground(new java.awt.Color(0, 0, 0));
        lbCoordenada6.setText("Bitácora");
        panelBotones.add(lbCoordenada6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 90, 40));

        add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, 1630, 300));

        jLabel5.setText("   0         1         2         3        4         5        6         7        8        9       10      11      12      13      14      15      16      17      18      19");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 650, -1));

        panelCoordinates.setForeground(new java.awt.Color(0, 0, 0));
        panelCoordinates.setOpaque(false);
        panelCoordinates.setLayout(new java.awt.GridLayout(20, 0));
        add(panelCoordinates, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 30, 640));

        jPanel6.setBackground(new java.awt.Color(165, 173, 167));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPlayer3.setBackground(new java.awt.Color(120, 120, 120));
        lbPlayer3.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        lbPlayer3.setForeground(new java.awt.Color(0, 0, 0));
        lbPlayer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayer3.setText("Player 3");
        lbPlayer3.setToolTipText("");
        lbPlayer3.setOpaque(true);
        lbPlayer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayer3MouseClicked(evt);
            }
        });
        jPanel6.add(lbPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 60));

        lbPlayer0.setBackground(new java.awt.Color(120, 120, 120));
        lbPlayer0.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        lbPlayer0.setForeground(new java.awt.Color(0, 0, 0));
        lbPlayer0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayer0.setText("Player 0");
        lbPlayer0.setToolTipText("");
        lbPlayer0.setOpaque(true);
        lbPlayer0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayer0MouseClicked(evt);
            }
        });
        jPanel6.add(lbPlayer0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 60));

        lbPlayer1.setBackground(new java.awt.Color(120, 120, 120));
        lbPlayer1.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        lbPlayer1.setForeground(new java.awt.Color(0, 0, 0));
        lbPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayer1.setText("Player 1");
        lbPlayer1.setToolTipText("");
        lbPlayer1.setOpaque(true);
        lbPlayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayer1MouseClicked(evt);
            }
        });
        jPanel6.add(lbPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 60));

        lbPlayer2.setBackground(new java.awt.Color(120, 120, 120));
        lbPlayer2.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        lbPlayer2.setForeground(new java.awt.Color(0, 0, 0));
        lbPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayer2.setText("Player 2");
        lbPlayer2.setToolTipText("");
        lbPlayer2.setOpaque(true);
        lbPlayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayer2MouseClicked(evt);
            }
        });
        jPanel6.add(lbPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 60));

        btnLoadSeaEnemy.setText("Load Sea");
        btnLoadSeaEnemy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadSeaEnemyMouseClicked(evt);
            }
        });
        jPanel6.add(btnLoadSeaEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, 60));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 20, 220, 660));
    }// </editor-fold>//GEN-END:initComponents

                                        

    private void btnCannonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCannonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCannonMouseClicked

    private void btnBombaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBombaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBombaMouseClicked

    private void btnTienda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienda3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTienda3ActionPerformed

    private void btnActivateChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivateChatMouseClicked
        // TODO add your handling code here:
        
        Utilities.cargarPanel(chatPanel, optionPanel);
        /*Peticion peticionIngresar = new Peticion(TipoAccion.ACTUALIZAR_CHAT, "");        
        Client conexion = new Client(peticionIngresar);
        
        Thread th = new Thread(){
        @Override
        public void run(){
            try {
                int i = 0;
                while(true){
                    Thread.sleep(500);
                    i++;
                    Object respuesta = conexion.getRespuestaServer();
                    if(respuesta != null){
                       txtChat.setText((String)respuesta);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        };th.start();*/
        Thread th = new Thread(){
        @Override
        public void run(){
            try {
                int i = 0;
                while(true){
                    Thread.sleep(800);
                    i++;
                    Peticion peticionIngresar = new Peticion(TipoAccion.ACTUALIZAR_CHAT, "");        
                    Client conexion = new Client(peticionIngresar);
                    Object respuesta = conexion.getRespuestaServer();
                    if(respuesta != null){
                       txtChat.setText((String)respuesta);
                    }else{
                        JOptionPane.showMessageDialog(null, "Los datos no coinciden!", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        };th.start();
    }//GEN-LAST:event_btnActivateChatMouseClicked

    private void btnSendMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMsgMouseClicked
        Message msg = new Message(MainWindow.player.getName(),txtMsg.getText());
        Peticion peticionIngresar = new Peticion(TipoAccion.SEND_MSG, msg);        
        Client conexion = new Client(peticionIngresar);
        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
           txtChat.setText((String)respuesta);
           txtMsg.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Los datos no coinciden!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSendMsgMouseClicked

    
    private void btnCannonMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCannonMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCannonMMouseClicked

    private void btnCannonBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCannonBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCannonBMouseClicked

    private void btnFireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFireMouseClicked
        // TODO add your handling code here:    
        String nombre ="";
        if(!btnFire.isEnabled() && (!btnHost.isEnabled() || !btnHost.isVisible())){
           return; 
        }
        if(lastEnemy == MainWindow.player.getId()){
            JOptionPane.showMessageDialog(null, "Bro usted no se puede disparar a si mismo!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(lastEnemy == -1){
             JOptionPane.showMessageDialog(null, "Debe selecionar un enemigo a disparar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
          
        if(lastUsed == 0){
            nombre = "Cannon";
        }else if(lastUsed == 1){
            nombre ="Cannon Multiple";
        }else if(lastUsed == 2){
            nombre ="Bomba";
        }else if(lastUsed == 3){
            nombre ="Cannon Barba Roja";
        }        
        
        MainWindow.armaUsada = MainWindow.player.buscarArma(nombre);
       
        if(MainWindow.armaUsada == null){
            JOptionPane.showMessageDialog(null, "No puede disparar porque no tiene esta arma!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            disparar();  
            panelCannonBR.setBackground(new Color(120,120,120));
            panelCannonM.setBackground(new Color(120,120,120));
            panelBomba.setBackground(new Color(120,120,120));
            panelCannon.setBackground(new Color(120,120,120));
            lastUsed =-1;
            lastEnemy = -1;
            lbPlayer0.setBackground(new Color(120,120,120));
            lbPlayer1.setBackground(new Color(120,120,120));
            lbPlayer2.setBackground(new Color(120,120,120));
            lbPlayer3.setBackground(new Color(120,120,120));
            flagCargado = false;
            MainWindow.setPlayerEnemigo();  
            MainWindow.finishTurn();
        }
               
             
    }//GEN-LAST:event_btnFireMouseClicked

    private void btnMercadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMercadoMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(MainWindow.contentPanel,MainWindow.panelTiendaMercado);
    }//GEN-LAST:event_btnMercadoMouseClicked

    private void btnMercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMercadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMercadoActionPerformed

    private void btnReadyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadyMouseClicked
        // TODO add your handling code here:
        if(MainWindow.player.grafo.hayFuente()){
            MainWindow.player.setReady(true);
            MainWindow.setPlayer();
            btnReady.setText("YOU ARE READY");
            btnReady.setEnabled(false);
        }else{
             JOptionPane.showMessageDialog(null, "No hay fuente de poder!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReadyMouseClicked

    private void btnHostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHostMouseClicked
        // TODO add your handling code here:
        
        if(!btnHost.isEnabled()){
           return; 
        }
        Peticion peticionIngresar = new Peticion(TipoAccion.CHECK_PLAYER_READY, "");        
        Client conexion = new Client(peticionIngresar);
        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
           if((boolean)respuesta){
               JOptionPane.showMessageDialog(null, "El juego ha iniciado!", "Error", JOptionPane.INFORMATION_MESSAGE);
               btnHost.setEnabled(false);               
           }else{
               JOptionPane.showMessageDialog(null, "Los jugadores no están listos!", "Error", JOptionPane.ERROR_MESSAGE);
           }
        }else{
            JOptionPane.showMessageDialog(null, "Los datos no coinciden!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHostMouseClicked

    private void panelCannonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCannonMouseClicked
        // TODO add your handling code here:
        panelCannonBR.setBackground(new Color(120,120,120));
        panelCannonM.setBackground(new Color(120,120,120));
        panelBomba.setBackground(new Color(120,120,120));
        panelCannon.setBackground(new Color(255,0,102));
        lastUsed = 0;
        
    }//GEN-LAST:event_panelCannonMouseClicked

    private void panelCannonMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCannonMMouseClicked
        // TODO add your handling code here:
        panelCannonBR.setBackground(new Color(120,120,120));
        panelCannonM.setBackground(new Color(255,0,102));
        panelBomba.setBackground(new Color(120,120,120));
        panelCannon.setBackground(new Color(120,120,120));
        lastUsed = 1;
    }//GEN-LAST:event_panelCannonMMouseClicked

    private void panelBombaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBombaMouseClicked
        // TODO add your handling code here:
        panelCannonBR.setBackground(new Color(120,120,120));
        panelCannonM.setBackground(new Color(120,120,120));
        panelBomba.setBackground(new Color(255,0,102));
        panelCannon.setBackground(new Color(120,120,120));
        lastUsed = 2;
    }//GEN-LAST:event_panelBombaMouseClicked

    private void panelCannonBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCannonBRMouseClicked
        // TODO add your handling code here:
        panelCannonBR.setBackground(new Color(255,0,102));
        panelCannonM.setBackground(new Color(120,120,120));
        panelBomba.setBackground(new Color(120,120,120));
        panelCannon.setBackground(new Color(120,120,120));
        lastUsed = 3;
    }//GEN-LAST:event_panelCannonBRMouseClicked

    private void lbPlayer0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayer0MouseClicked
        // TODO add your handling code here:
        lbPlayer0.setBackground(new Color(255,0,102));
        lbPlayer1.setBackground(new Color(120,120,120));
        lbPlayer2.setBackground(new Color(120,120,120));
        lbPlayer3.setBackground(new Color(120,120,120));
        lastEnemy = 0;
        
    }//GEN-LAST:event_lbPlayer0MouseClicked

    private void lbPlayer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayer1MouseClicked
        // TODO add your handling code here:
        lbPlayer0.setBackground(new Color(120,120,120));
        lbPlayer1.setBackground(new Color(255,0,102));
        lbPlayer2.setBackground(new Color(120,120,120));
        lbPlayer3.setBackground(new Color(120,120,120));
        lastEnemy = 1;
        
    }//GEN-LAST:event_lbPlayer1MouseClicked

    private void lbPlayer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayer2MouseClicked
        // TODO add your handling code here:
        lbPlayer0.setBackground(new Color(120,120,120));
        lbPlayer1.setBackground(new Color(120,120,120));
        lbPlayer2.setBackground(new Color(255,0,102));
        lbPlayer3.setBackground(new Color(120,120,120));
        lastEnemy = 2;
        
    }//GEN-LAST:event_lbPlayer2MouseClicked

    private void lbPlayer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayer3MouseClicked
        // TODO add your handling code here:
        lbPlayer0.setBackground(new Color(120,120,120));
        lbPlayer1.setBackground(new Color(120,120,120));
        lbPlayer2.setBackground(new Color(120,120,120));
        lbPlayer3.setBackground(new Color(255,0,102));
        lastEnemy = 3;
        
    }//GEN-LAST:event_lbPlayer3MouseClicked

    private void btnLoadSeaEnemyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadSeaEnemyMouseClicked
        // TODO add your handling code here:
        
         MainWindow.getPlayerEnemigo(lastEnemy);
         panelMar2.updateCanvas();
         flagCargado = true;
         
    }//GEN-LAST:event_btnLoadSeaEnemyMouseClicked
    private int randomX(){
        int min_val = 0;
        int max_val = 19;
        Random rand = new Random();
        int randX = min_val + rand.nextInt((max_val - min_val) + 1);
        return randX;
        
    }
    
    private int randomY(){
        int min_val = 0;
        int max_val = 19;
        Random rand = new Random();
        int randY = min_val + rand.nextInt((max_val - min_val) + 1);
        return randY;
    }
    private void disparar(){
        boolean flagCannonSimple = false;
        String bitacora = "";
        if (lastUsed == 0){
            bitacora += "\nArma Usada: Cannon Simple";
            int x = Integer.parseInt(txtCoordenadaX.getText());
            int y = Integer.parseInt(txtCoordenadaY.getText());
            bitacora += "\nPosiciones:   X = "+x+"    Y = "+y;
            for (Vertice v: MainWindow.enemigo.grafo.vertices) {
                for(Punto p: v.estructura.getCellsBusy()){
                    if(x == p.getX() && y == p.getY()){                        
                        flagCannonSimple = true;
                        MainWindow.enemigo.positions[x][y] = true;
                    }
                }
            }   
            if(flagCannonSimple){
                bitacora += "\nDisparo certero";
                bitacora += "\n---------------------------------------"; 
            }else{
                bitacora += "\nDisparo fallido";
                bitacora += "\n---------------------------------------"; 
            }
            
        }else if(lastUsed == 1){
            boolean flagCannonMultiple = false;
            boolean flagCannonMultiple2 = false;
            bitacora += "\nArma Usada: Cannon multiple";
            boolean bandera = false;
            int x = Integer.parseInt(txtCoordenadaX.getText());
            int y = Integer.parseInt(txtCoordenadaY.getText());
            bitacora += "\nPosiciones:   X = "+x+"    Y = "+y;
            for (Vertice v: MainWindow.enemigo.grafo.vertices) {
                for(Punto p: v.estructura.getCellsBusy()){
                    if(x == p.getX() && y == p.getY()){
                        bandera = true;
                        flagCannonMultiple2 = true;
                        MainWindow.enemigo.positions[x][y] = true;
                    }
                }
            }
            if(flagCannonMultiple2){
                bitacora += "\nDisparo certero";
                
            }else{
                bitacora += "\nDisparo fallido";
               
            }
            if (bandera){
                
                for (int i = 0; i < 4; i++) {
                    int newX = randomX();
                    int newY = randomY();
                    bitacora += "\n\tPosiciones:   X = "+newX+"    Y = "+newY;
                    for (Vertice v: MainWindow.enemigo.grafo.vertices) {
                        for(Punto p: v.estructura.getCellsBusy()){
                            if(newX == p.getX() && newY == p.getY()){
                                flagCannonMultiple = true;
                                MainWindow.enemigo.positions[newX][newY] = true;
                            }
                        }
                    }
                    if(flagCannonMultiple){
                        bitacora += "\n\tDisparo certero";
                        
                    }else{
                        bitacora += "\n\tDisparo fallido";
                        
            }
                    
                }
            }  bitacora += "\n-----------------------------------------------"; 
        }else if (lastUsed == 3){
            bitacora += "\nArma Usada: Cannon barba roja";
            boolean banderaCannonB = false;
            boolean banderaCannonB2 = false;
            boolean bandera = false;
            int x = Integer.parseInt(txtCoordenadaX.getText());
            int y = Integer.parseInt(txtCoordenadaY.getText());
            bitacora += "\nPosiciones:   X = "+x+"    Y = "+y;
            for (Vertice v: MainWindow.enemigo.grafo.vertices) {
                for(Punto p: v.estructura.getCellsBusy()){
                    if(x == p.getX() && y == p.getY()){
                        bandera = true;
                        banderaCannonB = true;
                        MainWindow.enemigo.positions[x][y] = true;

                    }
                }
            }
            if(banderaCannonB){
                bitacora += "\nDisparo certero";
                
                
            }else{
                bitacora += "\nDisparo fallido";
               
               
            }
            if (bandera){
                
                for (int i = 0; i < 10; i++) {
                    int newX = randomX();
                    int newY = randomY();
                    bitacora += "\n\tPosiciones:   X = "+newX+"    Y = "+newY;
                    for (Vertice v: MainWindow.enemigo.grafo.vertices) {
                        for(Punto p: v.estructura.getCellsBusy()){
                            if(newX == p.getX() && newY == p.getY()){
                                banderaCannonB2 = true;
                                MainWindow.enemigo.positions[newX][newY] = true;
                            }
                        }
                    }
                    if(banderaCannonB2){
                        bitacora += "\n\tDisparo certero";
                        
                    }else{
                        bitacora += "\n\tDisparo fallido";
                        
            }
                    
                }
            }  bitacora += "\n-----------------------------------------------";            
        }else if (lastUsed == 2){
            boolean banderaBomba = false;
            boolean banderaBomba2 = false;
            boolean banderaBomba3 = false;
            bitacora += "\nArma Usada: Bomba";
            String lasX = txtCoordenadaX.getText();
            String lasY = txtCoordenadaY.getText();
            
            String[] partsX = lasX.split(",");
            String x1 = partsX[0]; 
            String x2 = partsX[1]; 
            String x3 = partsX[2];
            
            String[] partsY = lasY.split(",");
            String y1 = partsY[0]; 
            String y2 = partsY[1]; 
            String y3 = partsY[2];
            
            for (Vertice v: MainWindow.enemigo.grafo.vertices) {
                for(Punto p: v.estructura.getCellsBusy()){
                    if(Integer.parseInt(x1) == p.getX() && Integer.parseInt(y1) == p.getY()){                        
                        banderaBomba = true;
                        MainWindow.enemigo.positions[Integer.parseInt(x1)][Integer.parseInt(y1)] = true;
                        
                    }else if(Integer.parseInt(x2) == p.getX() && Integer.parseInt(y2) == p.getY()){
                        
                        banderaBomba2 = true;
                        MainWindow.enemigo.positions[Integer.parseInt(x2)][Integer.parseInt(y2)] = true;                        
                        
                    }else if(Integer.parseInt(x3) == p.getX() && Integer.parseInt(y3) == p.getY()){
                        
                        banderaBomba3 = true;
                        MainWindow.enemigo.positions[Integer.parseInt(x3)][Integer.parseInt(y3)] = true;                       
                        
                    }
            
                }
            }
            bitacora += "\nPosiciones:   X = "+x1+"    Y = "+y1;            
            if(banderaBomba){
                bitacora += "\nDisparo certero";
            }else{
                bitacora += "\nDisparo fallido"; 
            }
            
            bitacora += "\nPosiciones:   X = "+x2+"    Y = "+y2;           
            if(banderaBomba2){
                bitacora += "\nDisparo certero";
            }else{
                bitacora += "\nDisparo fallido";
            }
             bitacora += "\nPosiciones:   X = "+x3+"    Y = "+y3;
            if(banderaBomba3){
                bitacora += "\nDisparo certero";
                bitacora += "\n---------------------------------------"; 

            }else{
                bitacora += "\nDisparo fallido";
                bitacora += "\n---------------------------------------"; 

            }
        }
        
        String textoAnterior = txtBitacora.getText();
        txtBitacora.setText(textoAnterior+bitacora);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activatePanel;
    private javax.swing.JLabel btnActivateChat;
    private javax.swing.JPanel btnBomba;
    private javax.swing.JPanel btnCannon;
    private javax.swing.JPanel btnCannonB;
    private javax.swing.JPanel btnCannonM;
    private javax.swing.JButton btnFire;
    private javax.swing.JButton btnHost;
    private javax.swing.JButton btnLoadSeaEnemy;
    private javax.swing.JButton btnMercado;
    private javax.swing.JButton btnReady;
    private javax.swing.JLabel btnSendMsg;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JPanel enemyPanel;
    private javax.swing.JLabel imgBomba;
    private javax.swing.JLabel imgCannon;
    private javax.swing.JLabel imgCannonB;
    private javax.swing.JLabel imgCannonM;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBarco;
    private javax.swing.JLabel lbBomba;
    private javax.swing.JLabel lbCannonB;
    private javax.swing.JLabel lbCannonM;
    private javax.swing.JLabel lbCantBomba;
    private javax.swing.JLabel lbCantCannon;
    private javax.swing.JLabel lbCantCannonB;
    private javax.swing.JLabel lbCantCannonM;
    private javax.swing.JLabel lbCañon;
    private javax.swing.JLabel lbCoordenada;
    private javax.swing.JLabel lbCoordenada2;
    private javax.swing.JLabel lbCoordenada4;
    private javax.swing.JLabel lbCoordenada5;
    private javax.swing.JLabel lbCoordenada6;
    private javax.swing.JLabel lbPlayer0;
    private javax.swing.JLabel lbPlayer1;
    private javax.swing.JLabel lbPlayer2;
    private javax.swing.JLabel lbPlayer3;
    private javax.swing.JLabel lbPlayerName;
    private javax.swing.JLabel lbState;
    private javax.swing.JPanel myPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel panelArmas;
    private javax.swing.JPanel panelBitacora;
    private javax.swing.JPanel panelBomba;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCannon;
    private javax.swing.JPanel panelCannonBR;
    private javax.swing.JPanel panelCannonM;
    private javax.swing.JPanel panelCoordinates;
    private javax.swing.JTextArea txtBitacora;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextField txtCoordenadaX;
    private javax.swing.JTextField txtCoordenadaY;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables
}
