/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ytces
 */
public class PanelArmas extends javax.swing.JPanel {

    /**
     * Creates new form PanelArmas
     */
    public PanelArmas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbPrecioMina = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        itemPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbPrecioMina1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        itemPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbPrecioMina2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        itemPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbPrecioMina3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        itemPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        itemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/canon.png"))); // NOI18N
        itemPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, 140));

        lbPrecioMina.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPrecioMina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecioMina.setText("500 kg acero ");
        itemPanel.add(lbPrecioMina, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cañón");
        itemPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, -1));

        add(itemPanel);

        itemPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        itemPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/canonMultiple.png"))); // NOI18N
        itemPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 190, 140));

        lbPrecioMina1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPrecioMina1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecioMina1.setText("1000 kg acero");
        itemPanel1.add(lbPrecioMina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cañón Mútiple");
        itemPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 210, -1));

        add(itemPanel1);

        itemPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        itemPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bomba.png"))); // NOI18N
        itemPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, 130));

        lbPrecioMina2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPrecioMina2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecioMina2.setText("2000 kg acero");
        itemPanel2.add(lbPrecioMina2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Bomba");
        itemPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, -1));

        add(itemPanel2);

        itemPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        itemPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cañonBarbaRoja.png"))); // NOI18N
        itemPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 150, -1));

        lbPrecioMina3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPrecioMina3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecioMina3.setText("5000 kg acero");
        itemPanel3.add(lbPrecioMina3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Cañón barba roja");
        itemPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 230, -1));

        add(itemPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemPanel;
    private javax.swing.JPanel itemPanel1;
    private javax.swing.JPanel itemPanel2;
    private javax.swing.JPanel itemPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbPrecioMina;
    private javax.swing.JLabel lbPrecioMina1;
    private javax.swing.JLabel lbPrecioMina2;
    private javax.swing.JLabel lbPrecioMina3;
    // End of variables declaration//GEN-END:variables
}
