/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Utilities;

/**
 *
 * @author muril
 */
public class PanelPublicaciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelPublicaciones
     */
    public PanelPublicaciones(String nombre, double precio, String imagen, String namePlayer) {
        initComponents();
        
        lbNombre.setText(nombre);
        lbPrecio.setText((String.valueOf(precio)));
        lbImagen.setIcon(Utilities.loadResizeIcon(imagen, 130));
        lbNamePlayer.setText(namePlayer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPrecio = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbNamePlayer = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbImagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 120, 120));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPrecio.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbPrecio.setText("Precio");
        add(lbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 126, 33));

        lbNombre.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbNombre.setText("Nombre");
        add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 159, 33));

        lbNamePlayer.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lbNamePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNamePlayer.setText("FERKS");
        add(lbNamePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 159, 33));

        jPanel1.setBackground(new java.awt.Color(212, 212, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImagen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/63877819.jpg"))); // NOI18N
        jPanel1.add(lbImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 130));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 200, 150));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbNamePlayer;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPrecio;
    // End of variables declaration//GEN-END:variables
}
