/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Utilities;

/**
 *
 * @author muril
 */
public class PanelTiendaMercado extends javax.swing.JPanel {
    
    public PanelTienda panelTienda;
    public PanelMercado panelMercado;

    /**
     * Creates new form PanelTiendaMercado
     */
    public PanelTiendaMercado() {
        initComponents();
        panelTienda = new PanelTienda();
        panelMercado = new PanelMercado();
        
        imgIntercambio.setIcon(Utilities.loadResizeIcon("src\\images\\mercado.png", 150));
        imgTienda.setIcon(Utilities.loadResizeIcon("src\\images\\tienda.png", 150));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTiendaMercado = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lbCañon6 = new javax.swing.JLabel();
        btnMercado = new javax.swing.JPanel();
        imgIntercambio = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbCañon8 = new javax.swing.JLabel();
        btnTienda = new javax.swing.JPanel();
        imgTienda = new javax.swing.JLabel();
        lbCañon7 = new javax.swing.JLabel();
        lbCañon9 = new javax.swing.JLabel();
        lbCañon10 = new javax.swing.JLabel();
        lbCañon11 = new javax.swing.JLabel();
        lbComprarMercado = new javax.swing.JLabel();
        lbBack = new javax.swing.JLabel();

        PanelTiendaMercado.setBackground(new java.awt.Color(165, 173, 167));

        jPanel9.setBackground(new java.awt.Color(165, 173, 167));

        lbCañon6.setBackground(new java.awt.Color(0, 0, 0));
        lbCañon6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCañon6.setForeground(new java.awt.Color(0, 0, 0));
        lbCañon6.setText("Mercado de intercambio");
        lbCañon6.setToolTipText("");

        btnMercado.setBackground(new java.awt.Color(212, 212, 212));
        btnMercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMercadoMouseClicked(evt);
            }
        });
        btnMercado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgIntercambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/canon.png"))); // NOI18N
        imgIntercambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgIntercambioMouseClicked(evt);
            }
        });
        btnMercado.add(imgIntercambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 160));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCañon6)
                    .addComponent(btnMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCañon6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(165, 173, 167));

        lbCañon8.setBackground(new java.awt.Color(0, 0, 0));
        lbCañon8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCañon8.setForeground(new java.awt.Color(0, 0, 0));
        lbCañon8.setText("Tienda comercial");
        lbCañon8.setToolTipText("");

        btnTienda.setBackground(new java.awt.Color(212, 212, 212));
        btnTienda.setMinimumSize(new java.awt.Dimension(190, 170));
        btnTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTiendaMouseClicked(evt);
            }
        });
        btnTienda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/canon.png"))); // NOI18N
        imgTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTiendaMouseClicked(evt);
            }
        });
        btnTienda.add(imgTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 150));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbCañon8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCañon8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbCañon7.setBackground(new java.awt.Color(0, 0, 0));
        lbCañon7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCañon7.setForeground(new java.awt.Color(0, 0, 0));
        lbCañon7.setText("Para comprar fábricas, armería, etc.");
        lbCañon7.setToolTipText("");

        lbCañon9.setBackground(new java.awt.Color(0, 0, 0));
        lbCañon9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCañon9.setForeground(new java.awt.Color(0, 0, 0));
        lbCañon9.setText("Tienda comercial");
        lbCañon9.setToolTipText("");

        lbCañon10.setBackground(new java.awt.Color(0, 0, 0));
        lbCañon10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCañon10.setForeground(new java.awt.Color(0, 0, 0));
        lbCañon10.setText("Mercado de intercambio");
        lbCañon10.setToolTipText("");

        lbCañon11.setBackground(new java.awt.Color(0, 0, 0));
        lbCañon11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbCañon11.setForeground(new java.awt.Color(0, 0, 0));
        lbCañon11.setText("Para intercambiar con otros jugadores sus armas o acero");
        lbCañon11.setToolTipText("");

        javax.swing.GroupLayout PanelTiendaMercadoLayout = new javax.swing.GroupLayout(PanelTiendaMercado);
        PanelTiendaMercado.setLayout(PanelTiendaMercadoLayout);
        PanelTiendaMercadoLayout.setHorizontalGroup(
            PanelTiendaMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTiendaMercadoLayout.createSequentialGroup()
                .addGroup(PanelTiendaMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTiendaMercadoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbCañon9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelTiendaMercadoLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbCañon7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelTiendaMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTiendaMercadoLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(lbCañon10, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGap(1613, 1613, 1613)))
            .addGroup(PanelTiendaMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTiendaMercadoLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(lbCañon11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1596, 1596, 1596)))
        );
        PanelTiendaMercadoLayout.setVerticalGroup(
            PanelTiendaMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTiendaMercadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCañon9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCañon7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(PanelTiendaMercadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelTiendaMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(PanelTiendaMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTiendaMercadoLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(lbCañon10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(239, Short.MAX_VALUE)))
            .addGroup(PanelTiendaMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTiendaMercadoLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(lbCañon11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );

        lbComprarMercado.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbComprarMercado.setForeground(new java.awt.Color(0, 0, 0));
        lbComprarMercado.setText("Opciones de mercados");

        lbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        lbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbComprarMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(787, 787, 787))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTiendaMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 1953, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbComprarMercado)
                    .addComponent(lbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(204, 204, 204)
                .addComponent(PanelTiendaMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imgIntercambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgIntercambioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgIntercambioMouseClicked

    private void btnMercadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMercadoMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(MainWindow.contentPanel, MainWindow.panelMercado);
    }//GEN-LAST:event_btnMercadoMouseClicked

    private void imgTiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTiendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgTiendaMouseClicked

    private void btnTiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiendaMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(MainWindow.contentPanel, MainWindow.panelTienda);
    }//GEN-LAST:event_btnTiendaMouseClicked

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        Utilities.cargarPanel(MainWindow.contentPanel, MainWindow.panelJuego);
    }//GEN-LAST:event_lbBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTiendaMercado;
    private javax.swing.JPanel btnMercado;
    private javax.swing.JPanel btnTienda;
    private javax.swing.JLabel imgIntercambio;
    private javax.swing.JLabel imgTienda;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbBack;
    private javax.swing.JLabel lbCañon10;
    private javax.swing.JLabel lbCañon11;
    private javax.swing.JLabel lbCañon6;
    private javax.swing.JLabel lbCañon7;
    private javax.swing.JLabel lbCañon8;
    private javax.swing.JLabel lbCañon9;
    private javax.swing.JLabel lbComprarMercado;
    // End of variables declaration//GEN-END:variables
}
