/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Utilities;
import javax.swing.JPanel;
import modelo.BarcoFantasma;

/**
 *
 * @author ytces
 */
public class PanelEnviarBarco extends javax.swing.JPanel {

    /**
     * Creates new form PanelEnviarBarco
     */
    public PanelEnviarBarco() {
        initComponents();
        PanelMar panel = new PanelMar(1);
        cargarPanel(panel);
    }
    
    public void cargarPanel(JPanel panel) {
        panelMar.removeAll();
        panelMar.add(panel);
        panelMar.repaint();
        panelMar.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMar = new javax.swing.JPanel();
        txtCoordenadaX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCoordenadaY = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnColocar = new javax.swing.JButton();
        lbBack = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMar.setLayout(new java.awt.GridLayout());
        add(panelMar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 640, 640));

        txtCoordenadaX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCoordenadaX.setText("5");
        txtCoordenadaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoordenadaXActionPerformed(evt);
            }
        });
        add(txtCoordenadaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 790, 190, 40));

        jLabel3.setText("Coordenada X");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 800, 110, 30));

        txtCoordenadaY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCoordenadaY.setText("6");
        txtCoordenadaY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoordenadaYActionPerformed(evt);
            }
        });
        add(txtCoordenadaY, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 840, 190, 40));

        jLabel2.setText("Coordenada Y");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 840, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese las coordenadas donde desea enviar el barco fantasma");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 1110, 70));

        btnColocar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnColocar.setText("Colocar");
        btnColocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColocarMouseClicked(evt);
            }
        });
        add(btnColocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 900, -1, -1));

        lbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        lbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });
        add(lbBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCoordenadaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoordenadaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoordenadaXActionPerformed

    private void txtCoordenadaYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoordenadaYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoordenadaYActionPerformed

    private void btnColocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColocarMouseClicked
        int x=0,y=0;
        try{
            x = Integer.parseInt(txtCoordenadaX.getText());
            y = Integer.parseInt(txtCoordenadaY.getText());
        }
        catch(NumberFormatException e){
            System.out.println("No se pudo convertir");
        }
        BarcoFantasma barco = new BarcoFantasma(x,y);
        barco.enviarBarco();
        MainWindow.player.subtractMoney(2500);
        Utilities.cargarPanel(MainWindow.contentPanel, MainWindow.panelJuego);
    }//GEN-LAST:event_btnColocarMouseClicked

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        Utilities.cargarPanel(MainWindow.contentPanel, MainWindow.panelTienda);
    }//GEN-LAST:event_lbBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColocar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbBack;
    private javax.swing.JPanel panelMar;
    private javax.swing.JTextField txtCoordenadaX;
    private javax.swing.JTextField txtCoordenadaY;
    // End of variables declaration//GEN-END:variables
}
