/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Utilities;
import java.awt.GridBagConstraints;

/**
 *
 * @author muril
 */
public class PanelVender extends javax.swing.JPanel {

    /**
     * Creates new form PanelVender
     */
    public PanelVender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        lbCoordenada4 = new javax.swing.JLabel();
        lbCoordenada6 = new javax.swing.JLabel();
        cboProductos = new javax.swing.JComboBox<>();
        lbSombrero = new javax.swing.JLabel();
        lbBandera = new javax.swing.JLabel();
        lbCoordenada5 = new javax.swing.JLabel();
        lbBack = new javax.swing.JLabel();
        lbCalavera = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotones.setBackground(new java.awt.Color(165, 173, 167));
        panelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, 30));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setBorder(null);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 30));

        lbCoordenada4.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lbCoordenada4.setForeground(new java.awt.Color(0, 0, 0));
        lbCoordenada4.setText("Indique el precio del producto que desea vender");
        jPanel1.add(lbCoordenada4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbCoordenada6.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lbCoordenada6.setForeground(new java.awt.Color(0, 0, 0));
        lbCoordenada6.setText("Indique el nombre del producto que desea vender");
        jPanel1.add(lbCoordenada6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cboProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cannon", "Cannon multiples", "Bomba", "Cannon barba roja", "Acero" }));
        jPanel1.add(cboProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, -1));

        panelBotones.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 460, 250));

        lbSombrero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbSombrero.setForeground(new java.awt.Color(0, 0, 0));
        lbSombrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sombrero.png"))); // NOI18N
        panelBotones.add(lbSombrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 140, 140));

        lbBandera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBandera.setForeground(new java.awt.Color(0, 0, 0));
        lbBandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bandera.png"))); // NOI18N
        panelBotones.add(lbBandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 10, 140, 140));

        add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 1630, 300));

        lbCoordenada5.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbCoordenada5.setForeground(new java.awt.Color(0, 0, 0));
        lbCoordenada5.setText("Vender en el mercado");
        add(lbCoordenada5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 250, -1));

        lbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        lbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });
        add(lbBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 70));

        lbCalavera.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbCalavera.setForeground(new java.awt.Color(0, 0, 0));
        lbCalavera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calavera.png"))); // NOI18N
        add(lbCalavera, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 270, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        String nombre = "";
        String imagen = "";
        double precio = 0.0;
        precio = Double.parseDouble(txtPrecio.getText());
        nombre = (String)cboProductos.getSelectedItem();
        
        if (nombre.equals("Cannon")){
            imagen = "src\\images\\canon.png"; 
        }else if (nombre.equals("Cannon multiples")){
            imagen = "src\\images\\canonMultiple.png";
        }else if(nombre.equals("Bomba")){
            imagen = "src\\images\\bomba.png";
        }else if(nombre.equals("Cannon barba roja")){
            imagen = "src\\images\\cañonBarbaRoja.png";
        }else if(nombre.equals("Acero")){
            imagen = "src\\images\\acero.png";
        }
        GridBagConstraints gbc = new GridBagConstraints();
                gbc.gridheight = GridBagConstraints.REMAINDER;
                gbc.weightx = 1;
                gbc.fill = GridBagConstraints.HORIZONTAL;
                MainWindow.panelComprar.mainList.add(new PanelPublicaciones(nombre,precio,imagen), gbc, 0);                
                MainWindow.panelComprar.panelPublicaciones.validate();
                MainWindow.panelComprar.panelPublicaciones.repaint();
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        Utilities.cargarPanel(MainWindow.contentPanel, MainWindow.panelMercado);
    }//GEN-LAST:event_lbBackMouseClicked

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    public static javax.swing.JComboBox<String> cboProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBack;
    private javax.swing.JLabel lbBandera;
    private javax.swing.JLabel lbCalavera;
    private javax.swing.JLabel lbCoordenada4;
    private javax.swing.JLabel lbCoordenada5;
    private javax.swing.JLabel lbCoordenada6;
    private javax.swing.JLabel lbSombrero;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
