/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlTienda;

/**
 *
 * @author ytces
 */
public class PanelEdificios extends javax.swing.JPanel {

    /**
     * Creates new form PanelEdificios
     */
    public PanelEdificios() {
        initComponents();
        generateEdificios();
    }
    
    public void generateEdificios(){
        String precio = "$"+ControlTienda.armeriaPrice;
        //PanelEdificioComprar panel = new PanelEdificioComprar(precio, "src\\images\\energySource.png");
        for(int i=0;i<6;i++){
            this.add(new PanelEdificioComprar(precio, "src\\images\\energySource.png"));  //no sirve esta verga
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
