/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Utilities;
import modelo.Templo;

/**
 *
 * @author ytces
 */
public class PanelMenu extends javax.swing.JPanel {
    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPlay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 120, 120));
        setPreferredSize(new java.awt.Dimension(1900, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Age of Pirates");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 620, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quit");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 250, 100));

        lbPlay.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        lbPlay.setForeground(new java.awt.Color(255, 255, 255));
        lbPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlay.setText("Play");
        lbPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayMouseClicked(evt);
            }
        });
        add(lbPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 250, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barcoInicio.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 330, 290));

        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 340, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void lbPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayMouseClicked
        Utilities.cargarPanel(MainWindow.contentPanel,MainWindow.panelStar);
        MainWindow.panelStar.contectarse();
        
    }//GEN-LAST:event_lbPlayMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Templo templo = new Templo(0, false, false);
        templo.generarComodin();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbPlay;
    // End of variables declaration//GEN-END:variables
}
