/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ytces
 */
public class PanelMar extends javax.swing.JPanel {
    private CanvasSea canvas;
    private int whoIs; //Mi canvas=0, Canvas enemigo = 1;
    /**
     * Creates new form PanelMar
     */
    public PanelMar(int whoIs) {
        initComponents();
        canvas = new CanvasSea(whoIs);        
        this.add(canvas);
        this.whoIs = whoIs;
    }
    
    public void updateCanvas(){
//        this.removeAll();
//        canvas = new CanvasSea(whoIs);
//        this.add(canvas);
        //canvas.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
